<a href="https://colab.research.google.com/github/ViratK18/Data-Science-January/blob/main/Copy_of_Copy_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
arr = np.array([1,2,3,4,5])

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
print(arr.ndim)

1


In [ ]:
arr.dtype

dtype('int64')

Time

In [ ]:
lst = [1]*10000

In [ ]:
print(lst)
print(len(lst))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [ ]:
arr = np.ones(10000,dtype="uint8")

In [ ]:
print(arr)

[1 1 1 ... 1 1 1]


In [ ]:
%timeit sum(lst)

10000 loops, best of 5: 66.4 µs per loop


In [ ]:
%timeit arr.sum()

The slowest run took 79.31 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 13.6 µs per loop


#Slicing

In [ ]:
arr = np.arange(5,25,2)

In [ ]:
print(arr)

[ 5  7  9 11 13 15 17 19 21 23]


In [ ]:
arr[2:5]

array([ 9, 11, 13])

In [ ]:
lst=[1,2,3,4,5]
lst2=lst[2:4]
print(lst)
print(lst2)
lst2[0]=1000
print(lst)
print(lst2)

[1, 2, 3, 4, 5]
[3, 4]
[1, 2, 3, 4, 5]
[1000, 4]


In [ ]:
arr=np.array([1,2,3,4,5])
arr2=arr[2:4]
print(arr)
print(arr2)
arr2[0]=1000
print(arr)
print(arr2)

[1 2 3 4 5]
[3 4]
[   1    2 1000    4    5]
[1000    4]


2D ARRAY

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr[0:1,1:3]

array([[2, 3]])

In [ ]:
arr[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [ ]:
arr=np.ones((2,3,4))

In [ ]:
arr.ndim

3

In [ ]:
arr.shape

(2, 3, 4)

Some more functions of Numpy

In [ ]:
arr=np.arange(10,20,2)

In [ ]:
arr

array([10, 12, 14, 16, 18])

In [ ]:
np.random.permutation(arr)

array([16, 12, 10, 18, 14])

In [ ]:
np.random.randint(1,5)

1

In [ ]:
arr = np.random.randn(1000)

In [ ]:
arr

array([ 3.58322910e-01,  3.71181565e-01,  1.49569096e+00, -8.05103899e-01,
       -7.24580187e-01,  1.90139866e-01, -5.02545436e-02,  2.35987682e-01,
       -7.89062717e-02,  1.81600354e+00, -1.02476743e+00,  6.13058751e-01,
        1.25279458e-01,  4.10360945e-01, -3.86106556e-01, -9.66656769e-01,
        1.32742372e+00, -1.38673696e-01,  2.75291995e-01, -2.15445196e+00,
       -9.13005777e-01, -5.36146023e-01,  9.03416506e-01,  7.29860792e-01,
       -6.58453762e-01, -4.73462675e-01,  2.05329286e-02, -1.08556225e+00,
        1.34948486e+00, -6.31961064e-01,  1.48013562e+00,  4.56899249e-01,
       -3.73632436e-01,  3.81154966e-01,  9.50671868e-01,  5.01981021e-01,
       -8.89917110e-01, -1.10668475e+00, -2.11511229e+00, -1.14420646e+00,
        7.12785224e-02,  2.66779333e-01, -4.86141840e-01,  5.75957052e-01,
       -3.78802667e-01, -2.50512303e+00,  9.24179147e-02, -2.74505858e-01,
       -2.26790884e+00, -9.64335882e-01, -6.88118343e-01,  1.58655738e+00,
        1.67105346e+00, -

In [ ]:
print(arr.mean(),arr.std())

-0.049510492436202105 0.9800539355365284


In [ ]:
arr=np.linspace(1,10,50)

In [ ]:
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
print(arr[6]-arr[5])
print(arr[40]-arr[39])

0.18367346938775508
0.1836734693877542


In [ ]:
arr=np.array([True,False,True,False,False])

In [ ]:
print(arr)

[ True False  True False False]


In [ ]:
np.where(arr,100,50)

array([100,  50, 100,  50,  50])

In [ ]:
arr=np.arange(1,10)

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.where(arr>5,100,90)

array([ 90,  90,  90,  90,  90, 100, 100, 100, 100])

In [ ]:
arr=np.zeros(20)

In [ ]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(20,)

In [ ]:
arr=arr.reshape(5,4)

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(5, 4)

In [ ]:
arr=arr.reshape(2,5,2)

In [ ]:
arr

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
arr.ndim

3

In [ ]:
arr.shape

(2, 5, 2)

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
a=np.array([1,2,34,4,5])
b=np.array([1,2,44,77,5])

In [ ]:
print(a>b)
print(a<b)
print(a==b)
print(a>=b)
print(a<=b)

[False False False False False]
[False False  True  True False]
[ True  True False False  True]
[ True  True False False  True]
[ True  True  True  True  True]


##BroadCasting

In [ ]:
a

array([ 1,  2, 34,  4,  5])

In [ ]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[ 3  4 36  6  7]
[-1  0 32  2  3]
[ 2  4 68  8 10]
[ 0.5  1.  17.   2.   2.5]


In [ ]:
arr2=np.arange(20).reshape(4,5)

In [ ]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a

array([ 1,  2, 34,  4,  5])

In [ ]:
a+arr2

array([[ 1,  3, 36,  7,  9],
       [ 6,  8, 41, 12, 14],
       [11, 13, 46, 17, 19],
       [16, 18, 51, 22, 24]])

In [ ]:
arr2*arr2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]])

## Fancy Indexing

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8])

In [ ]:
print(arr[1],arr[4],arr[6])

2 5 7


In [ ]:
arr[[1,4,6]]

array([2, 5, 7])

In [ ]:
idxArr=[1,4,6]

In [ ]:
arr[idxArr]

array([2, 5, 7])

In [ ]:
arr[[True,False,True,False,True,False,True,False]]

array([1, 3, 5, 7])

In [ ]:
arr[(arr>=2)&(arr<=5)]

array([2, 3, 4, 5])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
print(arr.mean())
print(arr.std())
print(arr.max())
print(arr.min())
print(arr.argmin())
print(arr.argmax())

4.5
2.29128784747792
8
1
0
7


In [ ]:
arr=np.arange(12).reshape(3,4)

In [ ]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#along the column 
arr.sum(axis=1)

array([ 6, 22, 38])

In [ ]:
#along the rows
arr.sum(axis=0)

array([12, 15, 18, 21])

In [ ]:
arr.argmin(axis=1)

array([0, 0, 0])

In [ ]:
np.cos(arr)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029,  0.75390225],
       [-0.14550003, -0.91113026, -0.83907153,  0.0044257 ]])

In [ ]:
x=np.arange(360)

In [ ]:
x

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
plt.plot(x,np.sin(np.deg2rad(x)))
plt.show()

NameError: ignored