<a href="https://colab.research.google.com/github/adityagupta1707/Data-Science-January/blob/Data-Science/Tensor_Flow_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

==> Tensorflow (Basic functions)
1. ANN Build
2. How to select number of hidden layers and neurons
3. Keras-Tuner (DL=> Randomised Search CV) 

In [3]:
import tensorflow as tf


In [4]:
print(tf.__version__)

2.8.0


In [5]:
import tensorflow as tf
print("TensorFlow version: {}".format(tf.__version__))
print("Keras version: {}".format(tf.keras.__version__))

TensorFlow version: 2.8.0
Keras version: 2.8.0


In [6]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [7]:
#define a variable
k=tf.constant(42)

In [8]:
k=tf.constant(1, dtype = tf.int64)

In [9]:
k

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [10]:
a=tf.constant([[4,2],[9,5]])

In [13]:
b=tf.constant(a)

In [12]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [16]:
print(tf.zeros(shape=(3,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [18]:
a1 = tf.constant([[3,4,5],[3,4,5]])
a2 = tf.constant([[1,2,3],[1,2,3]])

c=tf.add(a1,a2)

In [19]:
c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 6, 8],
       [4, 6, 8]], dtype=int32)>

In [20]:
#if we have to generate random number from normal distribution

tf.random.normal(shape=(2,2),mean=0,stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.3483549 ,  0.13906732],
       [ 1.2947963 , -0.6794235 ]], dtype=float32)>

In [21]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 7],
       [7, 9]], dtype=int32)>

In [23]:
a=tf.Variable(23)

In [24]:
a

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=23>

In [25]:
a2=tf.Variable([23])

In [26]:
a2

<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([23], dtype=int32)>

In [30]:
tensor = tf.Variable([ [ [10.,11.,12.],[13.,14.,15.],[16.,17.,18.],[19.,20.,21] ] ]) #tensor_variable

In [31]:
print(tensor.shape)

(1, 4, 3)


In [34]:
tensor1=(tf.reshape(tensor,[2,6]))

In [35]:
tensor1

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21.]], dtype=float32)>

In [37]:
#convert tensor to numpy

tensor.numpy()

array([[[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)

In [38]:
tensor1.numpy()

array([[10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21.]], dtype=float32)